# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
variables:
  resourceGroupName: 'Taskby-saad'
  location: 'East US'
  environmentName: 'Dev'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      name: 'restore'
      inputs:
        command: 'restore'
        projects: '**/*/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*/*.csproj'
        arguments: ''
    - task: ArchiveFiles@2
      name: 'archive1'
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure subscription 1(1)(bee78d4f-49f3-4648-893a-e2ca59d0cb33)'
        subscriptionId: 'bee78d4f-49f3-4648-893a-e2ca59d0cb33'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'Taskby-saad'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '*/Armtemplateforcontainerregistry.json'
        csmParametersFile: '*/registryparameters.json'
        deploymentMode: 'Incremental'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'containerregistry'
        publishLocation: 'Container'
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure subscription 1 (bee78d4f-49f3-4648-893a-e2ca59d0cb33)'
        subscriptionId: 'bee78d4f-49f3-4648-893a-e2ca59d0cb33'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'Taskby-saad'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '*/Armtemplateforwebapptemplate.json'
        csmParametersFile: '*/webapp.json'
        deploymentMode: 'Incremental'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        ArtifactName: 'webapp'
        publishLocation: 'Container'
- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploymentjob
    pool:
      vmImage: ubuntu-latest
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: containerregistry
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure subscription 1 (bee78d4f-49f3-4648-893a-e2ca59d0cb33)'
              appType: 'webApp'
              appName: 'webapp4269'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              deploymentMethod: 'auto'
